In [1]:
import pandas as pd

In [2]:
import os
print(os.getcwd())

C:\Users\Kotti\Machine_learning\Outliers

In [3]:
#df = pd.read_csv("/Untitled Folder 1/Outliers/heights.csv")
#df = pd.read_csv("http://localhost:8888/edit/Machine_learning/Outliers/heights.csv")
df = pd.read_csv("heights.csv")
df.head()

  gender     height
0   Male  73.847017
1   Male  68.781904
2   Male  74.110105
3   Male  71.730978
4   Male  69.881796

<h3 style='color:purple'>Detect outliers using percentile</h3>

In [4]:
max_thresold = df['height'].quantile(0.95)
max_thresold

72.61710606999999

In [5]:
df[df['height']>max_thresold]

      gender     height
0       Male  73.847017
2       Male  74.110105
23      Male  75.205974
27      Male  72.800844
31      Male  74.033808
...      ...        ...
4975    Male  73.339590
4977    Male  74.043290
4989    Male  72.726342
4994    Male  73.092871
7311  Female  73.389586

[500 rows x 2 columns]

In [6]:
min_thresold = df['height'].quantile(0.05)
min_thresold

60.246220829500004

In [7]:
df[df['height']<min_thresold]

      gender     height
1942    Male  59.981865
2191    Male  59.938650
2334    Male  59.380650
3020    Male  60.217019
4170    Male  60.243718
...      ...        ...
9978  Female  57.375759
9984  Female  59.047029
9988  Female  59.538729
9993  Female  60.030434
9994  Female  59.098250

[500 rows x 2 columns]

<h3 style='color:purple'>Remove outliers</h3>

In [8]:
df[(df['height']<max_thresold) & (df['height']>min_thresold)]

      gender     height
1       Male  68.781904
3       Male  71.730978
4       Male  69.881796
5       Male  67.253016
6       Male  68.785081
...      ...        ...
9995  Female  66.172652
9996  Female  67.067155
9997  Female  63.867992
9998  Female  69.034243
9999  Female  61.944246

[9000 rows x 2 columns]

<h3 style='color:purple'>Now lets explore banglore property prices dataset</h3>

In [9]:
df = pd.read_csv("bhp.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'bhp.csv'

In [ ]:
df.shape

In [10]:
df.describe()

             height
count  10000.000000
mean      66.367560
std        3.847528
min       54.263133
25%       63.505620
50%       66.318070
75%       69.174262
max       78.998742

**Explore samples that are above 99.90% percentile and below 1% percentile rank**

In [11]:
min_thresold, max_thresold = df.price_per_sqft.quantile([0.001, 0.999])
min_thresold, max_thresold

AttributeError: 'DataFrame' object has no attribute 'price_per_sqft'

In [ ]:
df[df.price_per_sqft < min_thresold]

In [ ]:
df[df.price_per_sqft > max_thresold]

<h3 style='color:purple'>Remove outliers</h3>

In [12]:
df2 = df[(df.price_per_sqft<max_thresold) & (df.price_per_sqft>min_thresold)]
df2.shape

AttributeError: 'DataFrame' object has no attribute 'price_per_sqft'

In [13]:
df2.describe()

NameError: name 'df2' is not defined

<h3 style='color:purple'>Exercise</h3>

Use this air bnb new york city [data set](https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data/data) and remove outliers using percentile based on price per night for a given apartment/home. You can use suitable upper and lower limits on percentile based on your intuition. 
Your goal is to come up with new pandas dataframe that doesn't have the outliers present in it.

[Solution](https://github.com/codebasics/py/tree/master/ML/FeatureEngineering/1_outliers/Exercise/1_outliers_percentile_exercise.ipynb)

In [16]:
nyc_df = pd.read_csv("AB_NYC_2019.csv")
nyc_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [17]:
nyc_df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [18]:
nyc_df.corr()

C:\Users\Kotti\AppData\Local\Temp\ipykernel_7984\682926835.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  nyc_df.corr()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
id,1.000000,0.588290,-0.003125,0.090908,0.010619,-0.013224,-0.319760,0.291828,0.133272,0.085468
host_id,0.588290,1.000000,0.020224,0.127055,0.015309,-0.017364,-0.140106,0.296417,0.154950,0.203492
latitude,-0.003125,0.020224,1.000000,0.084788,0.033939,0.024869,-0.015389,-0.010142,0.019517,-0.010983
longitude,0.090908,0.127055,0.084788,1.000000,-0.150019,-0.062747,0.059094,0.145948,-0.114713,0.082731
price,0.010619,0.015309,0.033939,-0.150019,1.000000,0.042799,-0.047954,-0.030608,0.057472,0.081829
minimum_nights,-0.013224,-0.017364,0.024869,-0.062747,0.042799,1.000000,-0.080116,-0.121702,0.127960,0.144303
number_of_reviews,-0.319760,-0.140106,-0.015389,0.059094,-0.047954,-0.080116,1.000000,0.549868,-0.072376,0.172028
reviews_per_month,0.291828,0.296417,-0.010142,0.145948,-0.030608,-0.121702,0.549868,1.000000,-0.009421,0.185791
calculated_host_listings_count,0.133272,0.154950,0.019517,-0.114713,0.057472,0.127960,-0.072376,-0.009421,1.000000,0.225701
availability_365,0.085468,0.203492,-0.010983,0.082731,0.081829,0.144303,0.172028,0.185791,0.225701,1.000000

In [19]:
nyc_df.shape

(48895, 16)

In [20]:
nyc_df.dropna()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
5,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48782,36425863,Lovely Privet Bedroom with Privet Restroom,83554966,Rusaa,Manhattan,Upper East Side,40.78099,-73.95366,Private room,129,1,1,2019-07-07,1.00,1,147
48790,36427429,No.2 with queen size bed,257683179,H Ai,Queens,Flushing,40.75104,-73.81459,Private room,45,1,1,2019-07-07,1.00,6,339
48799,36438336,Seas The Moment,211644523,Ben,Staten Island,Great Kills,40.54179,-74.14275,Private room,235,1,1,2019-07-07,1.00,1,87
48805,36442252,1B-1B apartment near by Metro,273841667,Blaine,Bronx,Mott Haven,40.80787,-73.92400,Entire home/apt,100,1,2,2019-07-07,2.00,1,40
48852,36455809,"Cozy Private Room in Bushwick, Brooklyn",74162901,Christine,Brooklyn,Bushwick,40.69805,-73.92801,Private room,30,1,1,2019-07-08,1.00,1,1

In [22]:
nyc_df.shape

(48895, 16)

In [23]:
min_nyc_thresold, max_nyc_thresold = nyc_df.price.quantile([0.001, 0.999])

In [24]:
min_nyc_thresold, max_nyc_thresold

(18.0, 3000.0)

In [26]:
nyc_df2 = nyc_df[(nyc_df.price<max_nyc_thresold) & (nyc_df.price>min_nyc_thresold)]
nyc_df2.shape

(48792, 16)

In [27]:
min_night,max_night=nyc_df2.minimum_nights.quantile([0.001, 0.95])

In [28]:
min_night,max_night

(1.0, 30.0)

In [31]:
nyc_df3 = nyc_df[(nyc_df.minimum_nights<max_night) & (nyc_df.minimum_nights>min_night)]

In [33]:
nyc_df3.shape

(31668, 16)